# Generated by Django 4.0.7 on 2022-09-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskmonitor", "0002_taskreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskQueue",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "queue",
                "managed": False,
            },
        ),
    ]
