# Generated by Django 4.0.7 on 2022-09-26 16:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskmonitor", "0003_taskqueue"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskQueued",
            fields=[
                ("app_name", models.CharField(max_length=255)),
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("priority", models.IntegerField(default=None, null=True)),
                ("task_id", models.UUIDField(default=uuid.uuid4)),
                ("task_name", models.CharField(max_length=255)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="TaskQueue",
        ),
    ]
