# Generated by Django 4.0.9 on 2023-02-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskmonitor", "0004_store_task_params_and_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="current_queue_length",
            field=models.IntegerField(
                default=None,
                help_text="Length of the queue at the time this log was created.",
                null=True,
            ),
        ),
    ]
