# Generated by Django 4.0.9 on 2023-02-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskmonitor", "0005_tasklog_current_queue_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="priority",
            field=models.IntegerField(
                db_index=True,
                default=None,
                help_text="Priority this task was executed with.",
                null=True,
            ),
        ),
    ]
