# Generated by Django 4.0.7 on 2022-10-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskmonitor", "0006_alter_tasklog_result"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasklog",
            old_name="task_args",
            new_name="args",
        ),
        migrations.RenameField(
            model_name="tasklog",
            old_name="task_kwargs",
            new_name="kwargs",
        ),
    ]
