# Generated by Django 5.2.15 on 2026-06-30 10:25

from django.db import migrations, models

import taskmonitor.core.json_encoders


class Migration(migrations.Migration):

    dependencies = [
        ("taskmonitor", "0008_taskstatistic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="args",
            field=models.JSONField(
                default=list,
                encoder=taskmonitor.core.json_encoders.UniversalJSONEncoder,
                help_text="Positional arguments the task was called with. Nested items might be truncated to [] or {}.",
            ),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="kwargs",
            field=models.JSONField(
                default=dict,
                encoder=taskmonitor.core.json_encoders.UniversalJSONEncoder,
                help_text="Keyword arguments the task was called with. Nested items might be truncated to [] or {}.",
            ),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="result",
            field=models.JSONField(
                default=None,
                encoder=taskmonitor.core.json_encoders.UniversalJSONEncoder,
                help_text="Result of the task.",
                null=True,
            ),
        ),
    ]
