# Generated by Django 4.0.7 on 2022-08-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskanalytics", "0002_tasklogentry_delete_tasklog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklogentry",
            name="runtime",
            field=models.FloatField(db_index=True, default=None, null=True),
        ),
    ]
