# Generated by Django 4.0.7 on 2022-08-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskanalytics", "0003_alter_tasklogentry_runtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklogentry",
            name="parent_task_id",
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="tasklogentry",
            name="priority",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tasklogentry",
            name="retries",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
