# Generated by Django 4.0.7 on 2022-08-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "taskanalytics",
            "0004_tasklogentry_parent_task_id_tasklogentry_priority_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasklogentry",
            old_name="parent_task_id",
            new_name="parent_id",
        ),
    ]
