# Generated by Django 4.0.7 on 2022-08-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskanalytics", "0005_rename_parent_task_id_tasklogentry_parent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklogentry",
            name="priority",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
